version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - postgres
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@postgres:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It's recommended to disable this in production.
      HASURA_GRAPHQL_DEV_MODE: "true"
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: tbqIwPZ_7rw
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "sSRiJYUp1Z_JqN6xqU7y0ohOC42H_D0X1AYjvUktO7c"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: Anonymous
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/chang/kiss/db_data
      o: bind 
